// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:4b05f411-7ff3-4c1a-a505-1937494307f5",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_ttCBMdX6I",
    "aws_user_pools_web_client_id": "68b3472i88jda1k3827v12oq1f"
};


export default awsmobile;
